#Ques2

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
arr=np.random.randn(4,4)

In [ ]:
arr

array([[ 0.31648622, -0.34301052,  0.56247247, -1.02168952],
       [ 1.06610304, -0.13846309,  1.61226028, -0.59305668],
       [ 0.07985729, -0.64066872, -1.28268706,  1.00430005],
       [ 0.74652123, -0.70681079,  0.1888633 ,  0.91516686]])

In [ ]:
#Part-(a)
arr.mean(axis=1)

array([-0.12143534,  0.48671089, -0.20979961,  0.28593515])

In [ ]:
arr.std(axis=1)

array([0.61625043, 0.8887206 , 0.85068719, 0.63305598])

In [ ]:
arr.var(axis=1)

array([0.37976459, 0.7898243 , 0.72366869, 0.40075988])

In [ ]:
#Part-(b)
B=[56,48,22,41,78,91,24,46,8,33]

In [ ]:
indices = np.argsort(B)

In [ ]:
indices

array([8, 2, 6, 9, 3, 7, 1, 0, 4, 5])

In [ ]:
#Part-(c)
n=int(input("Enter value of n  "))
m=int(input("Enter value of m  "))

arr=np.random.randint(0,10,size=(m,n))
arr

Enter value of n  4
Enter value of m  5


array([[3, 8, 8, 6],
       [9, 1, 8, 1],
       [1, 1, 0, 7],
       [2, 1, 6, 1],
       [8, 4, 0, 3]])

In [ ]:
arr.shape

(5, 4)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.reshape(n,m)

array([[3, 8, 8, 6, 9],
       [1, 8, 1, 1, 1],
       [0, 7, 2, 1, 6],
       [1, 8, 4, 0, 3]])

In [ ]:
#Part-(d)
zero=np.array(np.argwhere(arr==0))
zero

array([[2, 2],
       [4, 2]])

In [ ]:
non_zero=np.array(np.argwhere(arr!=0))
non_zero

array([[0, 0],
       [0, 1],
       [0, 2],
       [0, 3],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [2, 0],
       [2, 1],
       [2, 3],
       [3, 0],
       [3, 1],
       [3, 2],
       [3, 3],
       [4, 0],
       [4, 1],
       [4, 3]])

In [ ]:
nan_val=np.array(np.argwhere(arr=='NaN'))
nan_val

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  """Entry point for launching an IPython kernel.


array([], shape=(0, 0), dtype=int64)